<?php
/** @var Mirakl\SalesChannels\Block\Adminhtml\System\Config\Form\Field\ChannelMapping $block */
?>
<?php
$htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$stores = $block->getStores();
$channels = $block->getMiraklChannels();
?>
<div class="design_theme_ua_regexp" id="grid<?= $block->escapeHtmlAttr($htmlId) ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= $block->escapeHtmlAttr($block->getElement()->getId()) ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?= $block->escapeHtml($column['label']) ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($stores as $store): ?>
                <?php
                    /** @var \Magento\Store\Model\Store $store */
                    $website = $store->getWebsite();
                    $group = $store->getGroup();
                ?>
                <tr>
                    <td>
                        <input type="hidden"
                               name="groups[sales_channels][fields][mirakl_channels][value][<?= /* @noEscape */ $store->getCode() ?>][store_code]"
                               value="<?= /* @noEscape */ $store->getCode() ?>">
                        <div><?= /* @noEscape */ $website->getName() ?></div>
                        <div style="padding-left:10px;color:#aaa;"><?= /* @noEscape */ $group->getName() ?></div>
                        <div style="padding-left:20px;">
                            <label for="channel_<?= /* @noEscape */ $store->getCode() ?>"><strong><?= /* @noEscape */ $store->getName() ?></strong></label><br>
                            <em><?= __('(code: %1)', /* @noEscape */ $store->getCode()) ?></em>
                        </div>
                    </td>
                    <td>
                        <select id="channel_<?= /* @noEscape */ $store->getCode() ?>" name="groups[sales_channels][fields][mirakl_channels][value][<?= /* @noEscape */ $store->getCode() ?>][channel_code]"
                                class="admin__control-select required-entry">
                            <?php $storeChannel = $block->getSelectedChannel($store->getCode()) ?>
                            <option value=""<?= !$storeChannel ? ' selected' : '' ?>><?= $block->escapeHtml(__('-- Select Channel --')) ?></option>
                            <?php foreach ($channels as $channel): ?>
                                <option value="<?= /* @noEscape */ $channel->getCode() ?>"<?= $storeChannel === $channel->getCode() ? ' selected' : '' ?>>
                                    <?= $block->escapeHtml($channel->getLabel()) ?>&nbsp;(<?= /* @noEscape */ $channel->getCode() ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
