<?php
/** @var Mirakl\FrontendDemo\Block\Shop\View $block */
/** @var Mirakl\Core\Model\Shop $_shop */
$_shop = $block->getShop();
$_info = $_shop->getAdditionalInfo();
?>
<div class="seller-shop">
    <table class="data table additional-attributes" id="contact-info-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Contact Information') ?></caption>
        <tbody>
            <?php if ($_proInfo = $_info->getProfessionalInfo()): ?>
                <?php $_proInfo = (array) $_proInfo; ?>
                <?php if (isset($_proInfo['corporate_name'])): ?>
                    <tr>
                        <td><strong><?= /* @escapeNotVerified */ __('Corporate Name') ?></strong></td>
                        <td><?= /* @escapeNotVerified */ $_proInfo['corporate_name'] ?></td>
                    </tr>
                <?php endif ?>
                <?php if (isset($_proInfo['identification_number'])): ?>
                    <tr>
                        <td><strong><?= /* @escapeNotVerified */ __('Identification Number') ?></strong></td>
                        <td><?= /* @escapeNotVerified */ $_proInfo['identification_number'] ?></td>
                    </tr>
                <?php endif ?>
            <?php endif ?>

            <?php if ($_info->getDataByKey('contact_info')): ?>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Address'); ?></strong></td>
                    <td>
                        <?= /* @escapeNotVerified */ $_info['contact_info']['street_1'] ?><br>
                        <?php if (!empty($_info['contact_info']['street_2'])): ?>
                            <?= /* @escapeNotVerified */ $_info['contact_info']['street_2'] ?><br>
                        <?php endif ?>
                        <?= /* @escapeNotVerified */ $_info['contact_info']['zip_code'] ?> <?= /* @escapeNotVerified */ $_info['contact_info']['city'] ?><br>
                        <?= /* @escapeNotVerified */ isset($_info['contact_info']['state']) ? $_info['contact_info']['state'] : '' ?>
                    </td>
                </tr>
            <?php else: ?>
                <tr>
                    <td colspan="2"><?= /* @escapeNotVerified */ __('Seller has no contact information') ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
