<?php
/** @var Mirakl\FrontendDemo\Block\Shop\FavoriteRankOffers $block */
$_products = $block->getProductCollection();
?>
<?php if ($_products && $_products->count() === 0): ?>
    <?= /* @escapeNotVerified */ __('The seller has no favorite products') ?>
<?php else: ?>
<div class="block widget new">
    <div class="block-content content" aria-labelledby="block-widget new-heading">
        <div class="products wrapper grid products-grid products-new-grid">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($_products as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info">
                    <?php $_productUrl = $block->getProductUrl($_product) ?>
                    <?php $_productName = $block->escapeHtml($_product->getName()) ?>
                    <a href="<?= /* @escapeNotVerified */ $_productUrl ?>" class="product photo product-item-photo">
                        <?php $productImage = $block->getImage($_product, 'new_products_content_widget_grid') ?>
                        <?= !$productImage ?: $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" title="<?= /* @escapeNotVerified */ $_productName ?>" href="<?= /* @escapeNotVerified */ $_productUrl ?>">
                                <?= /* @escapeNotVerified */ $_productName ?>
                            </a>
                        </strong>
                    </div>
                </div>
                <?= ($iterator == count($_products)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif; ?>