<?php
/** @var Mirakl\FrontendDemo\Block\Shop\View $block */
/** @var Mirakl\Core\Model\Shop $_shop */
$_shop = $block->getShop();
$_info = $_shop->getAdditionalInfo();
?>
<div class="block-content">
    <?php if ($_info->getDataByKey('return_policy')): ?>
        <?= /* @escapeNotVerified */ nl2br($_info->getDataByKey('return_policy')) ?>
    <?php else: ?>
        <?= /* @escapeNotVerified */ __('Seller has no return policy') ?>
    <?php endif; ?>
</div>
