<?php

/**
 * @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block
 * @var \Magento\Framework\Data\Form\Element\Fieldset $_element
 * @codingStandardsIgnoreFile
 */
?>
<?php $_element = $block->getElement() ?>
<div class="rule-tree">
    <fieldset id="<?= $_element->getHtmlId() ?>" <?= /* @escapeNotVerified */ $_element->serialize(['class']) ?> class="fieldset">
        <legend class="legend"><span><?= /* @escapeNotVerified */ $_element->getLegend() ?></span></legend>
        <br>
    <?php if ($_element->getComment()): ?>
        <div class="messages">
            <div class="message message-notice"><?= $block->escapeHtml($_element->getComment()) ?></div>
        </div>
    <?php endif; ?>
    <div class="rule-tree-wrapper">
        <?= $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?= $_element->getHtmlId() ?> = new VarienRulesForm('<?= $_element->getHtmlId() ?>', '<?= /* @escapeNotVerified */ $block->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()): ?>
    <?= $_element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>

});
</script>
