<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Catalog\Model\Product $saleableItem */

$saleableItem = $block->getSaleableItem();
$productId = $saleableItem->getId();
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view');

/** @var \Magento\Framework\Pricing\Helper\Data $pricingHelper */
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$mainOffer = $saleableItem->getData('main_offer');

$mainOfferId = $mainOffer ? $mainOffer->getId() : '';
$minShippingPrice = $mainOffer ? $mainOffer->getMinShippingPrice() : 0;

/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $this->helper('Magento\Tax\Helper\Data');

/** @var \Mirakl\FrontendDemo\Helper\Tax $miraklTaxHelper */
$miraklTaxHelper = $this->helper('Mirakl\FrontendDemo\Helper\Tax');

/** @var \Mirakl\Connector\Helper\Config $config */
$config = $this->helper('Mirakl\Connector\Helper\Config');

/** @var \Mirakl\FrontendDemo\Helper\Offer $offerHelper */
$offerHelper = $this->helper('Mirakl\FrontendDemo\Helper\Offer');

if ($config->getShippingPricesIncludeTax()) {
    $minShippingPriceInclTax = $minShippingPrice;
    $minShippingPriceExclTax = $miraklTaxHelper->getShippingPriceExclTax($minShippingPrice);
} else {
    $minShippingPriceInclTax = $miraklTaxHelper->getShippingPriceInclTax($minShippingPrice);
    $minShippingPriceExclTax = $minShippingPrice;
}
?>

<?php if ($block->hasSpecialPrice()): ?>
    <span class="special-price" style="display: inline-block;">
        <?php if (!$mainOffer || $offerHelper->isOperatorProductAvailable($saleableItem)): ?>
            <?= /* @escapeNotVerified */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema'            => $schema
            ]); ?>
        <?php else: ?>
            <?= $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
                ->setProduct($saleableItem)
                ->setOffer($mainOffer)
                ->setDisplayShippingPrice(false)
                ->toHtml();
            ?>
        <?php endif ?>
    </span>
    <span class="offer-wrapper">
        <span class="offer-min-shipping-price offer-shipping best-offer-shipping" data-shipping-offer-id="<?= /* @escapeNotVerified */ $mainOfferId ?>"></span>
    </span>
<div>
    <span class="old-price">
        <?= /* @escapeNotVerified */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
</div>

<?php else: ?>
    <?php if (!$mainOffer || $offerHelper->isOperatorProductAvailable($saleableItem)): ?>
        <?= /* @escapeNotVerified */ $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema'            => $schema
        ]); ?>
    <?php else: ?>
        <?= /* @escapeNotVerified */ $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
            ->setProduct($saleableItem)
            ->setOffer($mainOffer)
            ->setDisplayShippingPrice(false)
            ->toHtml();
        ?>
    <?php endif ?>

    <span class="offer-wrapper">
        <span class="offer-min-shipping-price offer-shipping best-offer-shipping" data-shipping-offer-id="<?= /* @escapeNotVerified */ $mainOfferId ?>"></span>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a href="<?= /* @escapeNotVerified */ $saleableItem->getProductUrl(); ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal(); ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal(); ?>
        </span>
    <?php endif; ?>
<?php endif; ?>

<div class="offer-price-description" <?php if (!$mainOffer || !$offerHelper->isOperatorProductAvailable($saleableItem)): ?>style="display: none;"<?php endif ?>>
    <?= /* @escapeNotVerified */ $mainOffer ? $mainOffer->getPriceAdditionalInfo() : '' ?>
</div>
