<?php
/**
 * @var \Mirakl\Adminhtml\Block\Sales\Order\View\Items\Column\Mirakl $block
 * @var \Mirakl\Connector\Helper\Tax $taxHelper
 */
$item = $block->getItem();
$order = $item->getOrder();
$taxHelper = $this->helper('Mirakl\Connector\Helper\Tax');
?>
<?php if (!$item->getMiraklShopId()): ?>
    <?= /* @escapeNotVerified */ __('N/A') ?>
<?php else: ?>
    <dl class="item-options">
        <dt><strong><?= /* @escapeNotVerified */ __('Offer: ') ?></strong></dt>
        <dd><?= /* @escapeNotVerified */ $item->getMiraklOfferId() ?></dd>

        <dt><strong><?= /* @escapeNotVerified */ __('Shop: ') ?></strong></dt>
        <dd><?= /* @escapeNotVerified */ $item->getMiraklShopName() ?> (<?= /* @escapeNotVerified */ $item->getMiraklShopId() ?>)</dd>

        <dt class="nobr"><strong><?= /* @escapeNotVerified */ __('Shipping Method: ') ?></strong></dt>
        <dd><?= /* @escapeNotVerified */ $item->getMiraklShippingTypeLabel() ?></dd>

        <dt class="nobr"><strong><?= /* @escapeNotVerified */ __('Shipping Charges: ') ?></strong></dt>
        <dd>
            <?php if ($taxHelper->displaySalesShippingBoth() || $taxHelper->displaySalesShippingExclTax()): ?>
                <div class="price-excl-tax">
                    <?php if ($taxHelper->displaySalesShippingBoth()): ?>
                        <span class="label"><?= /* @escapeNotVerified */ __('Excl. Tax'); ?>:</span>
                    <?php endif; ?>

                    <?= /* @escapeNotVerified */ $order->formatBasePrice($block->getItemBaseShippingPriceExclTax()) ?>

                    <?php if ($order->isCurrencyDifferent()): ?>
                        [<?= /* @escapeNotVerified */ $order->formatPrice($block->getItemShippingPriceExclTax()) ?>]
                    <?php endif ?>
                </div>
            <?php endif ?>

            <?php if ($taxHelper->displaySalesShippingBoth() || $taxHelper->displaySalesShippingInclTax()): ?>
                <div class="price-incl-tax">
                    <?php if ($taxHelper->displaySalesShippingBoth()): ?>
                        <span class="label"><?= /* @escapeNotVerified */ __('Incl. Tax'); ?>:</span>
                    <?php endif; ?>

                    <?= /* @escapeNotVerified */ $order->formatBasePrice($block->getItemBaseShippingPriceInclTax()) ?>

                    <?php if ($order->isCurrencyDifferent()): ?>
                        [<?= /* @escapeNotVerified */ $order->formatPrice($block->getItemShippingPriceInclTax()) ?>]
                    <?php endif ?>
                </div>
            <?php endif ?>

            <?php if ($item->getMiraklBaseShippingTaxAmount()): ?>
                <div class="tax-amount">
                    <span class="label"><?= /* @escapeNotVerified */ __('Tax'); ?>:</span>

                    <?= /* @escapeNotVerified */ $order->formatBasePrice($item->getMiraklBaseShippingTaxAmount()) ?>

                    <?php if ($order->isCurrencyDifferent()): ?>
                        [<?= /* @escapeNotVerified */ $order->formatPrice($item->getMiraklShippingTaxAmount()) ?>]
                    <?php endif ?>
                </div>
            <?php endif ?>
        </dd>
    </dl>
<?php endif ?>