<?php /* @var \Magento\Catalog\Block\Product\View\AbstractView $block */?>

<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php $offer = $_product->getData('main_offer'); ?>
    <div class="stock available offer" title="<?= $block->escapeHtml(__('Availability')) ?>"<?php if (!$offer): ?> style="display: none;"<?php endif; ?>>
        <span class="stock-available-offer"><?= /* @escapeNotVerified */ $offer ? $offer->getQuantity() : '' ?></span>&nbsp;<span><?= /* @escapeNotVerified */ __('In Stock') ?></span>
    </div>
    <div class="offer-state" title="<?= $block->escapeHtml(__('Offer State')) ?>"<?php if (!$offer): ?> style="display: none;"<?php endif; ?>>
        <span class="offer-state-label"><?= /* @escapeNotVerified */ $offer ? __($offer->getConditionName()) : '' ?></span>
    </div>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>"<?php if ($offer): ?> style="display: none;"<?php endif; ?>>
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>"<?php if ($offer): ?> style="display: none;"<?php endif; ?>>
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
