<?php
/** @var \Mirakl\FrontendDemo\Block\Order\SalesList $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info');?>

<?php $block->getChildBlock('sales.order.history.list')->setOrders($_orders)->setHtmlClassName('history');?>
<?= $block->getChildHtml('sales.order.history.list');?>

<?php if ($_orders && count($_orders)): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.'); ?></span></div>
<?php endif ?>
