<?php
/** @var \Magento\Sales\Block\Order\Items $block */
$_order = $block->getOrder();
if ($_order->getMiraklSent()) {
    $this->helper('Mirakl\FrontendDemo\Helper\Order')->filterOrderTotals($_order);
}
$_items = $_order->getItemsCollection();
$_index = 0;
$_count = $_items->count();
$_giftMessage = '';
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= /* @escapeNotVerified */ __('Items Ordered') ?>">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items Ordered') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                <th class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th class="col price"><?= /* @escapeNotVerified */ __('Price') ?></th>
                <th class="col qty"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                <th class="col subtotal"><?= /* @escapeNotVerified */ __('Subtotal') ?></th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php /** @var \Magento\Sales\Model\Order\Item $_item */ ?>
            <?php if ($_item->getParentItem() || ($_item->getMiraklOfferId() && $_order->getData('mirakl_sent'))) continue; ?>

            <tbody>
                <?= $block->getItemHtml($_item) ?>

                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
                    <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                               id="order-item-gift-message-link-<?= /* @escapeNotVerified */ $_item->getId() ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $_item->getId() ?>"
                               data-item-id="<?= /* @escapeNotVerified */ $_item->getId() ?>">
                                <?= /* @escapeNotVerified */ __('Gift Message') ?>
                            </a>
                            <div class="order-gift-message" id="order-item-gift-message-<?= /* @escapeNotVerified */ $_item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?= /* @escapeNotVerified */ __('Close') ?>"
                                   aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                   data-item-id="<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                   class="action close">
                                    <?= /* @escapeNotVerified */ __('Close') ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?= /* @escapeNotVerified */ __('From') ?></strong><?= $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?= /* @escapeNotVerified */ __('To') ?></strong><?= $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?= /* @escapeNotVerified */ $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_item) ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
</div>
<?php if ($_giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
