<?php /** @var \Mirakl\FrontendDemo\Block\Order\Info $block */ ?>
<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <?php if (!empty($block->getMiraklOrder()->getShipping()->getTrackingUrl())): ?>
            <a href="<?= $block->escapeUrl($block->getMiraklOrder()->getShipping()->getTrackingUrl()) ?>"
               class="action track"
               title="<?= $block->escapeHtmlAttr(__('Track your order')) ?>"
               target="_blank"><span><?= $block->escapeHtmlAttr(__('Track your order')) ?></span></a>
        <?php endif; ?>
        <?php if ($this->canReceiveOrder()): ?>
            <a class="action mark-as-received"
               href="<?= $block->escapeHtml($this->getMarkAsReceivedUrl()) ?>"
               onclick="return confirm('<?= $this->escapeJsQuote(__('Are you sure?')) ?>')">
                <span><?= $this->escapeHtml(__('Mark Order As Received')) ?></span>
            </a>
        <?php endif; ?>
    </div>
</div>
