<?php
/** @var \Mirakl\FrontendDemo\Block\Order\SalesList $block */
/** @var \Magento\Sales\Block\Order\History $_parentBlock */
/** @var \Mirakl\Connector\Helper\Order $_orderHelper */
$_orders = $block->getOrders();
$_storeName = $block->getStoreName();
$_parentBlock = $block->getParentBlock();
$_orderHelper = $this->helper('Mirakl\Connector\Helper\Order');
?>
<?php if ($_orders && count($_orders)): ?>
<div class="table-wrapper orders-<?= $block->getHtmlClassName() ?>">
    <table class="data table table-order-items <?= $block->getHtmlClassName() ?>" id="my-orders-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                <th scope="col" class="col shop"><?= /* @escapeNotVerified */ __('Shop') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $block->addMiraklOrdersToCollection(); ?>
            <?php /** @var \Magento\Sales\Model\Order $_order */ ?>
            <?php foreach ($_orders as $_order): ?>
                <?php $_isFullMiraklOrder = $_orderHelper->isFullMiraklOrder($_order); ?>
                <tr class="main">
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"></td>
                    <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Shop')) ?>" class="col shop"></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions"></td>
                </tr>
                <?php if (!$_isFullMiraklOrder || !$_order->getData('mirakl_sent')): ?>
                <tr class="magento">
                    <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col date">
                        <span class="flag magento"><?= /* @escapeNotVerified */ __('Magento') ?></span>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"></td>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                        <?php
                            // Remove Mirakl orders amounts from the order only if order has been sent to Mirakl
                            if ($_order->getData('mirakl_sent')) {
                                $this->helper('Mirakl\FrontendDemo\Helper\Order')->filterOrderTotals($_order);
                            }
                        ?>
                        <?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Shop')) ?>" class="col shop"><?= $block->escapeHtml($_storeName) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                        <?= /* @escapeNotVerified */ $_order->getStatusLabel() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= /* @escapeNotVerified */ $_parentBlock->getViewUrl($_order) ?>" class="action view">
                            <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                        </a>
                    </td>
                </tr>
                <?php endif ?>
    
                <?php if (is_array($_order->getMiraklOrders()) && count($_order->getMiraklOrders())): ?>
                    <?php /** @var \Mirakl\MMP\FrontOperator\Domain\Order $_miraklOrder */ ?>
                    <?php foreach ($_order->getMiraklOrders() as $_miraklOrder): ?>
                        <tr class="marketplace">
                            <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col date">
                                <span class="flag marketplace"><?= /* @escapeNotVerified */ __('Marketplace') ?></span>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_miraklOrder->getId() ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"></td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                                <?= /* @escapeNotVerified */ $_order->formatPrice($_orderHelper->getMiraklTotalPrice($_order, $_miraklOrder)) ?>
                            </td>
    	                    <td data-th="<?= $block->escapeHtml(__('Shop')) ?>" class="col shop"><?= $this->escapeHtml($_miraklOrder->getShopName()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                                <?= /* @escapeNotVerified */ __($_miraklOrder->getStatus()->getState()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?= /* @escapeNotVerified */ $block->getMiraklOrderViewUrl($_order, $_miraklOrder) ?>" class="action view">
                                    <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif ?>
