<?php
/** @var \Mirakl\FrontendDemo\Block\Order\Info $block */
/** @var \Mirakl\MMP\FrontOperator\Domain\Order $_miraklOrder */
/** @var \Magento\Sales\Model\Order $_order */
$_miraklOrder = $this->getMiraklOrder();
$_order = $this->getOrder();
$_shipping = $_miraklOrder->getShipping();
$_shippingPrice = $this->helper('Mirakl\Connector\Helper\Order')->getMiraklShippingPriceInclTax($_order, $_miraklOrder);
$_baseShippingPrice = $this->helper('Mirakl\Connector\Helper\Order')->getMiraklBaseShippingPriceInclTax($_order, $_miraklOrder);
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Shipping Information') ?></strong>
    </div>
    <div class="block-content">
        <p><strong><?= /* @escapeNotVerified */ __('Shipping Method: ') ?></strong><?= /* @escapeNotVerified */ $_shipping->getType()->getLabel() ?><p>
        <p><strong><?= /* @escapeNotVerified */ __('Shipping Price: ') ?></strong><?= /* @escapeNotVerified */ $_shippingPrice > 0 ? $_order->formatPrice($_shippingPrice) : __('Free') ?><?php if ($_order->isCurrencyDifferent()): ?> [<?= /* @escapeNotVerified */ $_order->formatBasePrice($_baseShippingPrice) ?>]<?php endif ?></p>
        <?php if (!empty($_shipping->getTrackingUrl())): ?>
            <p><strong><?= /* @escapeNotVerified */ __('Shipping Company: ') ?></strong><?= /* @escapeNotVerified */ $_shipping->getCarrier() ?>
            <p><strong><?= /* @escapeNotVerified */ __('Shipping Tracking: ') ?></strong><?= /* @escapeNotVerified */ $_shipping->getTrackingNumber() ?>
            <p><strong><?= /* @escapeNotVerified */ __('Shipping URL: ') ?></strong><a href="<?= $block->escapeUrl($_shipping->getTrackingUrl()) ?>" name="tracking_url">
                <?= /* @escapeNotVerified */ $_shipping->getTrackingUrl() ?>
            </a>
        <?php else: ?>
            <p><strong><?= /* @escapeNotVerified */ __('The carrier selected by the seller and tracking information will be available after your order is shipped.') ?></strong></p>
        <?php endif ?>
    </div>
</div>