<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:ignoreFile

?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $this->helper('Mirakl\Connector\Helper\Tax')->getCalculatedTaxes($_order);
    global $taxIter; $taxIter++;
?>

<?php if ($_fullInfo && $block->displayFullSummary()): ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $title      = $info['title'];
            ?>
            <tr class="totals tax details details-<?= /* @escapeNotVerified */ $taxIter; ?> <?php echo($block->getIsPlaneMode()) ? ' plane' : '';?>">
                <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?>>
                    <?= $block->escapeHtml($title); ?>
                    <?php if (!is_null($percent)): ?>
                        (<?= (float) $percent; ?>%)
                    <?php endif; ?>
                    <br />
                </td>
                <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> rowspan="1">
                    <?= /* @escapeNotVerified */ $_order->formatPrice($amount); ?>
                </td>
            </tr>
        <?php endforeach; ?>
<?php endif; ?>

<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary plane">
<?php else: ?>
<tr class="totals-tax">
<?php endif; ?>
    <th <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> scope="row">
        <?php if ($block->displayFullSummary()): ?>
            <div class="detailed"><?= /* @escapeNotVerified */ __('Tax'); ?></div>
        <?php else: ?>
            <?= /* @escapeNotVerified */ __('Tax'); ?>
        <?php endif; ?>
    </th>
    <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml(__('Tax')); ?>">
        <?= /* @escapeNotVerified */ $_order->formatPrice($_source->getTaxAmount()) ?>
    </td>
</tr>
