<?php
/** @var \Mirakl\FrontendDemo\Block\Order\View $block */
/** @var \Mirakl\Connector\Helper\Order $_orderHelper */
/** @var \Mirakl\Connector\Helper\Tax $_taxHelper */
/** @var \Mirakl\Api\Helper\Reason $_reasonHelper */
$_miraklOrder = $block->getMiraklOrder();
$_order = $block->getOrder();
$_locale = $this->helper('Mirakl\Core\Helper\Config')->getLocale();
$_reasonHelper = $this->helper('Mirakl\Api\Helper\Reason');
$_orderHelper = $this->helper('Mirakl\Connector\Helper\Order');
$_taxHelper = $this->helper('Mirakl\Connector\Helper\Tax');
$hasRejectedItems = $block->hasRejectedMiraklItems();
$hasRefunds = $block->hasMiraklRefunds();
$hasCancelations = $block->hasCancelations();
?>
<div class="order-details-items ordered">
<div class="order-title">
    <strong><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></strong>
</div>
<div class="table-wrapper order-items">
<table class="data table table-order-items" id="my-orders-table" summary="<?php /* @escapeNotVerified */ echo __('Items Ordered') ?>">
<caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></caption>
<thead>
    <tr>
        <th class="col name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
        <th class="col incident"><?php /* @escapeNotVerified */ echo __('Incident') ?></th>
        <th class="col sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
        <th class="col price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
        <th class="col qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
        <th class="col subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal') ?></th>
    </tr>
</thead>
<tbody>
<?php foreach ($_miraklOrder->getOrderLines() as $_orderLine): ?>
<?php
    /** @var \Mirakl\MMP\FrontOperator\Domain\Order\OrderLine $_orderLine */
    $_hasIncident = $_orderHelper->isOrderLineIncident($_orderLine);
    $_isRefused   = $_orderHelper->isOrderLineRefused($_orderLine);
?>
<?php $orerItemClass = $_hasIncident ? 'incident': ($_isRefused ? 'refused' : '') ?>
<tr id="order-item-row-<?= /* @escapeNotVerified */ $_orderLine->getId() ?>" class="<?= $orerItemClass ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_orderLine->getOffer()->getProduct()->getTitle()) ?></strong>
    </td>
    <td class="col incident" data-th="<?php echo $block->escapeHtml(__('Incident')); ?>">
        <?php if (!$_orderLine->getCanOpenIncident() && !$_hasIncident): ?>
            <?php echo __('N/A') ?>
        <?php else: ?>
            <?php if (!$_hasIncident): ?>
                <?= __('No open incidents') ?>
                <?= $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Message\OpenIncident::class)
                    ->setMiraklOrderLineId($_orderLine->getId())
                    ->toHtml() ?>
            <?php else: ?>
                <?php
                    $_jsFormObject = 'incidentForm' . $_orderLine->getId();
                    $_route        = '*/*/postIncident';
                    $_reasons      = $_reasonHelper->getCloseIncidentReasons($_locale);
                    $_url          = $this->getUrl($_route, [
                        'type'      => 'close',
                        'order_id'  => $_order->getId(),
                        'remote_id' => $_miraklOrder->getId()
                    ]);
                ?>
                <form action="<?= /* @escapeNotVerified */ $_url ?>" id="incident-<?= $_orderLine->getId() ?>" class="incident-form" method="post">
                    <?php echo $block->getBlockHtml('formkey'); ?>
                    <input type="hidden" name="order_line_id" value="<?php echo $_orderLine->getId() ?>" />
                    <p><?php echo __($_orderLine->getStatus()->getReason()->getLabel()) ?></p>
                    <select name="reason" title="<?php /* @escapeNotVerified */ echo __('Incident') ?>" data-validate="{'validate-select':true}">
                        <option value=""><?php echo __('-- Close Incident --') ?></option>
                        <?php foreach ($_reasons as $_reason): ?>
                            <?php /** @var \Mirakl\MMP\FrontOperator\Domain\Reason $_reason */ ?>
                            <option value="<?php echo $_reason->getCode() ?>"><?php echo $this->escapeHtml($_reason->getLabel()) ?></option>
                        <?php endforeach ?>
                    </select>
                    <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('OK') ?></span></button>
                </form>
                <script type="text/x-magento-init">
                    {
                        "#incident-<?php echo $_orderLine->getId() ?>": {
                           "Mirakl_FrontendDemo/js/order/incident-form": {}
                        }
                    }
                </script>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?= $this->escapeHtml($_orderLine->getOffer()->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')); ?>">
        <?php if ($_taxHelper->displaySalesPricesInclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                <?php echo $_order->formatPrice($block->getOrderLinePrice($_orderLine)) ?>
            </span>
        <?php endif ?>

        <?php if ($_taxHelper->displaySalesPricesExclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                <?php echo $_order->formatPrice($block->getOrderLinePriceExclTax($_orderLine)) ?>
            </span>
    <?php endif ?>
    </td>
    <?php $isOrderLineHasCancelations = $_orderHelper->isOrderLineCanceled($_orderLine) ?>
    <?php $isOrderLineRefused = $_orderHelper->isOrderLineRefused($_orderLine) ?>
    <?php if ($isOrderLineHasCancelations) : ?>
        <?php $totalQty = $_orderHelper->getOrderLineTotalQuantity($_orderLine) ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
            <s><?= $totalQty ?></s>
            <span><?= $_orderLine->getQuantity() ?></span>
        </td>
    <?php else : ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
            <?= $_orderLine->getQuantity() ?>
        </td>
    <?php endif; ?>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
    <?php if ($isOrderLineHasCancelations) : ?>
        <?php // crossed orderLines subtotals ?>
        <?php if ($_taxHelper->displaySalesPricesInclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <s class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                <?php echo $_order->formatPrice($block->getOrderLineTotalPrice($_orderLine)) ?>
            </s>
        <?php endif ?>
        <?php if ($_taxHelper->displaySalesPricesExclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <s class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                <?php echo $_order->formatPrice($block->getOrderLineTotalPriceExclTax($_orderLine)) ?>
            </s>
        <?php endif ?>
        <?php //orderLines subtotals after cancelations ?>
        <?php if ($_taxHelper->displaySalesPricesInclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                <?= $block->formatFinalPrice($block->getOrderLinePriceAfterCancelationInclTax($_orderLine)) ?>
            </span>
        <?php endif ?>
        <?php if ($_taxHelper->displaySalesPricesExclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                              <?= $block->formatFinalPrice($_orderLine->getPrice()) ?>
             </span>
        <?php endif ?>
    <?php else :?>
        <?php if ($_taxHelper->displaySalesPricesInclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                 <?= $_order->formatPrice($block->getOrderLineTotalPrice($_orderLine)) ?>
             </span>
        <?php endif ?>
        <?php if ($_taxHelper->displaySalesPricesExclTax() || $_taxHelper->displaySalesPricesBoth()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                <?= $_order->formatPrice($block->getOrderLineTotalPriceExclTax($_orderLine)) ?>
            </span>
        <?php endif ?>
    <?php endif;?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
<tfoot class="<?= $hasCancelations || $hasRejectedItems ? 'with-crossed-out-prices' : '' ?>">
<?php if ($hasCancelations || $hasRejectedItems) : ?>
    <?php if (!$_taxHelper->displaySalesSubtotalBoth()): ?>
    <tr class="subtotal">
        <th colspan="5" class="mark" scope="row"><?= __('Subtotal') ?></th>
        <td class="amount" data-th="<?= __('Subtotal') ?>">
            <s>
                <?= $_order->formatPrice(
                    $_taxHelper->displaySalesSubtotalInclTax()
                        ? $block->getOrderSubtotalPrice()
                        : $block->getOrderSubtotalPriceExclTax()
                ) ?>
            </s>
            <span>
                <?= $block->formatFinalPrice(
                    $_taxHelper->displaySalesSubtotalInclTax()
                        ? $block->getOrderFinalSubtotalInclTax()
                        : $block->getOrderFinalSubtotalExclTax()
                ) ?>
            </span>
        </td>
    </tr>
    <?php else: ?>
        <tr class="subtotal_excl">
            <th colspan="5" class="mark" scope="row"><?= __('Subtotal (Excl. Tax)') ?></th>
            <td class="amount" data-th="<?= __('Subtotal (Excl. Tax)') ?>">
                <s>
                    <?= $_order->formatPrice($block->getOrderSubtotalPriceExclTax()) ?>
                </s>
                <span>
                     <?= $block->formatFinalPrice($block->getOrderFinalSubtotalExclTax()) ?>
                </span>
            </td>
        </tr>
        <tr class="subtotal_incl">
            <th colspan="5" class="mark" scope="row"><?= __('Subtotal (Incl. Tax)') ?></th>
            <td class="amount" data-th="<?= __('Subtotal (Incl. Tax)') ?>">
                <s>
                    <?= $_order->formatPrice($block->getOrderSubtotalPrice()) ?>
                </s>
                <span>
                     <?= $block->formatFinalPrice($block->getOrderFinalSubtotalInclTax()) ?>
                </span>
            </td>
        </tr>
    <?php endif ?>
<?php else : ?>
    <?php if (!$_taxHelper->displaySalesSubtotalBoth()): ?>
        <tr class="subtotal">
            <th colspan="5" class="mark" scope="row"><?php echo __('Subtotal') ?></th>
            <td class="amount" data-th="<?php echo __('Subtotal') ?>">
                <?= $_order->formatPrice(
                    $_taxHelper->displaySalesSubtotalInclTax() ?
                        $block->getOrderSubtotalPrice() :
                        $block->getOrderSubtotalPriceExclTax()
                ) ?>
            </td>
        </tr>
    <?php else: ?>
            <tr class="subtotal_excl">
                <th colspan="5" class="mark" scope="row"><?php echo __('Subtotal (Excl. Tax)') ?></th>
                <td class="amount" data-th="<?= __('Subtotal (Excl. Tax)') ?>">
                    <?= $_order->formatPrice($block->getOrderSubtotalPriceExclTax()) ?>
                </td>
            </tr>
            <tr class="subtotal_incl">
                <th colspan="5" class="mark" scope="row"><?php echo __('Subtotal (Incl. Tax)') ?></th>
                <td class="amount" data-th="<?php echo __('Subtotal (Incl. Tax)') ?>">
                    <?= $_order->formatPrice($block->getOrderSubtotalPrice()) ?>
                </td>
            </tr>
    <?php endif ?>
<?php endif; ?>
<?php $orderShippingPriceInclTax = $block->getOrderShippingPriceInclTax() ?>
<?php $orderShippingPriceExclTax = $block->getOrderShippingPriceExclTax() ?>
<?php if ($hasCancelations || $hasRejectedItems) : ?>
    <?php $originalShippingPriceInclTax = $block->getOrderShippingPriceInclTax() ?>
    <?php $finalShippingPriceInclTax = $block->getOrderFinalShippingPriceInclTax() ?>
    <?php $orderFinalShippingPriceInclTax = $block->getOrderFinalShippingPriceInclTax() ?>
    <?php $orderFinalShippingPriceExclTax = $block->getOrderFinalShippingPriceExclTax() ?>
    <?php $displayCrossedOutShippingPrice = $originalShippingPriceInclTax !== $finalShippingPriceInclTax ?>
    <?php if (!$_taxHelper->displaySalesSubtotalBoth()): ?>
    <tr class="shipping">
        <th colspan="5" class="mark" scope="row"><?= __('Shipping & Handling') ?></th>
        <td class="amount" data-th="<?= __('Shipping & Handling') ?>">
            <?php // we display shipping crossed prices only if there was cancelations / rejections on shipping fees ?>
            <?php if ($displayCrossedOutShippingPrice) : ?>
                <s>
                    <?= $_order->formatPrice(
                        $_taxHelper->displaySalesShippingInclTax()
                            ? $orderShippingPriceInclTax
                            : $orderShippingPriceExclTax
                    ) ?>
                </s>
            <?php endif;?>
                <span>
                    <?= $block->formatFinalPrice(
                        $_taxHelper->displaySalesShippingInclTax()
                            ? $orderFinalShippingPriceInclTax
                            : $orderFinalShippingPriceExclTax
                    ) ?>
                </span>
        </td>
     </tr>
     <?php else: ?>
        <tr class="shipping_excl">
            <th colspan="5" class="mark" scope="row"><?= __('Shipping & Handling (Excl. Tax)') ?></th>
            <td class="amount" data-th="<?= __('Shipping & Handling (Excl. Tax)') ?>">
                <?php if ($displayCrossedOutShippingPrice) : ?>
                    <s>
                        <?= $_order->formatPrice($orderShippingPriceExclTax) ?>
                    </s>
                <?php endif; ?>
                    <span>
                        <?= $block->formatFinalPrice($orderFinalShippingPriceExclTax) ?>
                    </span>
            </td>
        </tr>
        <tr class="shipping_incl">
            <th colspan="5" class="mark" scope="row"><?= __('Shipping & Handling (Incl. Tax)') ?></th>
            <td class="amount" data-th="<?= __('Shipping & Handling (Incl. Tax)') ?>">
                <?php if ($displayCrossedOutShippingPrice) : ?>
                    <s>
                        <?= $_order->formatPrice($orderShippingPriceInclTax) ?>
                    </s>
                <?php endif; ?>
                    <span>
                        <?= $block->formatFinalPrice($orderFinalShippingPriceInclTax) ?>
                    </span>
            </td>
        </tr>
     <?php endif ?>
<?php else: ?>
    <?php if (!$_taxHelper->displaySalesSubtotalBoth()): ?>
        <tr class="shipping">
            <th colspan="5" class="mark" scope="row"><?php echo __('Marketplace Shipping') ?></th>
            <td class="amount" data-th="<?php echo __('Marketplace Shipping') ?>">
                <?= $_order->formatPrice(
                    $_taxHelper->displaySalesShippingInclTax()
                        ? $orderShippingPriceInclTax
                        : $orderShippingPriceExclTax
                     ) ?>
            </td>
        </tr>
    <?php else: ?>
            <tr class="shipping_excl">
                <th colspan="5" class="mark" scope="row"><?php echo __('Marketplace Shipping (Excl. Tax)') ?></th>
                <td class="amount" data-th="<?php echo __('Marketplace Shipping (Excl. Tax)') ?>">
                    <?= $_order->formatPrice($orderShippingPriceExclTax) ?>
                </td>
            </tr>
            <tr class="shipping_incl">
                <th colspan="5" class="mark" scope="row"><?php echo __('Marketplace Shipping (Incl. Tax)') ?></th>
                <td class="amount" data-th="<?php echo __('Marketplace Shipping (Incl. Tax)') ?>">
                    <?= $_order->formatPrice($orderShippingPriceInclTax) ?>
                </td>
            </tr>
    <?php endif ?>
<?php endif; ?>
<?php if ($hasCancelations || $hasRejectedItems) : ?>
    <?php if ($_taxHelper->displaySalesFullSummary($_order->getStore())): ?>
        <?php $_taxDetails = $_taxHelper->getMiraklFinalCalculatedTaxes($_order, $_miraklOrder) ?>
            <?php if (!empty($_taxDetails)): ?>
                <tr class="grand_total">
                    <th colspan="5" class="mark" scope="row"><strong><?= __('Grand Total (Excl. Tax)') ?></strong></th>
                    <td class="amount" data-th="<?= __('Grand Total (Excl. Tax)') ?>">
                        <s>
                            <strong><?= $_order->formatPrice($block->getOrderTotalPriceExclTax()) ?></strong>
                        </s>
                        <span>
                            <strong><?= $_order->formatPrice($block->getOrderFinalTotalPriceExclTax()) ?></strong>
                        </span>
                    </td>
                </tr>
                <?php foreach ($_taxDetails as $_tax): ?>
                    <tr class="totals tax details">
                        <th colspan="5" class="mark" scope="row"><?= $block->escapeHtml($_tax['title']) ?></th>
                        <td class="amount" data-th="<?= $block->escapeHtml($_tax['title']) ?>">
                            <?= $_order->formatPrice($_tax['tax_amount']) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <?php $_miraklOrderTaxDetails = $_taxHelper->getMiraklOrderFinalCalculatedTaxes($_order, $_miraklOrder) ?>
                <?php if (!empty($_miraklOrderTaxDetails)): ?>
                    <tr class="grand_total">
                        <th colspan="5" class="mark" scope="row"><strong><?= __('Grand Total (Excl. Tax)') ?></strong></th>
                        <td class="amount" data-th="<?= __('Grand Total (Excl. Tax)') ?>">
                            <s>
                                <strong><?= $_order->formatPrice($block->getOrderTotalPriceExclTax()) ?></strong>
                            </s>
                            <span>
                                 <strong><?= $block->formatFinalPrice($block->getOrderFinalTotalPriceExclTax()) ?></strong>
                            </span>
                        </td>
                    </tr>
                    <?php foreach ($_miraklOrderTaxDetails as $_tax): ?>
                        <tr class="totals tax details">
                            <th colspan="5" class="mark" scope="row">
                                <?= __('%1 (%2%)', $block->escapeHtml($_tax['title']), round($_tax['percent'], 2)) ?>
                            </th>
                            <td class="amount" data-th="<?= $block->escapeHtml($_tax['title']) ?>">
                                <s>
                                    <?= $_order->formatPrice($_tax['tax_amount']) ?>
                                </s>
                                <span>
                                    <?= $block->formatFinalPrice($_tax['final_tax_amount']) ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
            <?php endif ?>
        <?php endif ?>
    <?php endif ?>
<?php else : ?>
    <?php if ($_taxHelper->displaySalesFullSummary($_order->getStore())): ?>
        <?php $_taxDetails = $_taxHelper->getMiraklCalculatedTaxes($_order) ?>
        <?php if (!empty($_taxDetails)): ?>
            <tr class="grand_total">
                <th colspan="5" class="mark" scope="row"><strong><?php echo __('Grand Total (Excl. Tax)') ?></strong></th>
                <td class="amount" data-th="<?php echo __('Grand Total (Excl. Tax)') ?>">
                    <strong><?php echo $_order->formatPrice($block->getOrderTotalPriceExclTax()) ?></strong>
                </td>
            </tr>
            <?php foreach ($_taxDetails as $_tax): ?>
                <tr class="totals tax details">
                    <th colspan="5" class="mark" scope="row"><?php echo $block->escapeHtml($_tax['title']) ?></th>
                    <td class="amount" data-th="<?php echo $block->escapeHtml($_tax['title']) ?>">
                        <?php echo $_order->formatPrice($_tax['tax_amount']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <?php $_miraklOrderTaxDetails = $_taxHelper->getMiraklOrderCalculatedTaxes($_order, $_miraklOrder) ?>
            <?php if (!empty($_miraklOrderTaxDetails)): ?>
                <tr class="grand_total">
                    <th colspan="5" class="mark" scope="row"><strong><?php echo __('Grand Total (Excl. Tax)') ?></strong></th>
                    <td class="amount" data-th="<?php echo __('Grand Total (Excl. Tax)') ?>">
                        <strong><?php echo $_order->formatPrice($block->getOrderTotalPriceExclTax()) ?></strong>
                    </td>
                </tr>
                <?php foreach ($_miraklOrderTaxDetails as $_tax): ?>
                <tr class="totals tax details">
                    <th colspan="5" class="mark" scope="row">
                        <?php echo __('%1 (%2%)', $block->escapeHtml($_tax['title']), round($_tax['percent'], 2)) ?>
                    </th>
                    <td class="amount" data-th="<?php echo $block->escapeHtml($_tax['title']) ?>">
                        <?php echo $_order->formatPrice($_tax['tax_amount']) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php endif ?>
        <?php endif ?>
    <?php endif ?>
<?php endif; ?>
<?php if ($hasCancelations || $hasRejectedItems) : ?>
    <tr class="tax">
        <th colspan="5" class="mark" scope="row"><?php echo __('Tax Total') ?></th>
        <td class="amount" data-th="<?php echo __('Tax Total') ?>">
            <s>
                <?= $_order->formatPrice($block->getOrderTotalTax()) ?>
            </s>
            <span>
                    <?= $block->formatFinalPrice($block->getMiraklFinalTotalTax()) ?>
            </span>
        </td>
    </tr>
<?php else : ?>
    <tr class="tax">
        <th colspan="5" class="mark" scope="row"><?php echo __('Tax Total') ?></th>
        <td class="amount" data-th="<?php echo __('Tax Total') ?>"><?php echo $_order->formatPrice($block->getOrderTotalTax()) ?></td>
    </tr>
<?php endif; ?>
<?php if ($hasCancelations || $hasRejectedItems) : ?>
    <tr class="grand_total last">
        <th colspan="5" class="mark" scope="row"><strong><?= __('Grand Total') ?></strong></th>
        <td class="amount" data-th="<?= __('Grand Total') ?>">
            <s>
                <strong><?= $_order->formatPrice($block->getOrderTotalPrice()) ?></strong>
            </s>
            <span>
                 <strong><?= $block->formatFinalPrice($block->getOrderFinalTotalPriceInclTax()) ?></strong>
             </span>
        </td>
    </tr>
<?php else: ?>
    <tr class="grand_total last">
        <th colspan="5" class="mark" scope="row"><strong><?= __('Grand Total') ?></strong></th>
        <td class="amount" data-th="<?= __('Grand Total') ?>">
            <strong><?= $_order->formatPrice($block->getOrderTotalPrice()) ?></strong>
        </td>
    </tr>
<?php endif; ?>
<?php if ($_order->isCurrencyDifferent()): ?>
        <?php if ($hasCancelations || $hasRejectedItems) : ?>
        <tr class="base_grandtotal">
            <th colspan="5" class="mark" scope="row"><?= __('Grand Total to be Charged') ?></th>
            <td class="amount" data-th="<?= __('Grand Total to be Charged') ?>">
                <s>
                    <?= $_order->formatBasePrice($block->getOrderBaseTotalPrice()) ?>
                </s>
                <span>
                    <?= $_order->formatBasePrice($block->getOrderFinalBaseTotalPrice()) ?>
                </span>
            </td>
        </tr>
        <?php else: ?>
        <tr class="base_grandtotal">
            <th colspan="5" class="mark" scope="row"><?php echo __('Grand Total to be Charged') ?></th>
            <td class="amount" data-th="<?php echo __('Grand Total to be Charged') ?>">
                <?= $_order->formatBasePrice($block->getOrderBaseTotalPrice()) ?>
            </td>
        </tr>
        <?php endif; ?>
<?php endif ?>
<?php if ($hasRefunds): ?>
    <tr class="tax">
        <th colspan="5" class="mark" scope="row"><?= __('Refunded Total') ?></th>
        <td class="amount" data-th="<?= __('Refunded Total') ?>">
            <?= $_order->formatPrice($block->getMiraklRefundTotal()) ?>
        </td>
    </tr>
    <tr class="grand_total last">
        <th colspan="5" class="mark" scope="row"><strong><?php echo __('Total Paid') ?></strong></th>
        <td class="amount" data-th="<?= __('Total Paid') ?>">
            <strong><?= $block->formatFinalPrice($block->getMiraklPaidTotal()) ?></strong>
        </td>
    </tr>
<?php endif; ?>
</tfoot>
</table>
</div>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getBackUrl() ?>">
            <span><?php /* @escapeNotVerified */ echo $block->getBackTitle() ?></span>
        </a>
    </div>
</div>
</div>
