<?php
/** @var \Mirakl\FrontendDemo\Block\Product\View\Tab\Offers $block */
$product = $block->getProduct();
$offers = $block->getAllOffers();
$operatorOffers = $block->getOperatorOffers();
/** @var \Magento\Catalog\Block\Product\View $productView */
$productView = $block->getLayout()->getBlock('product.info');
?>
<?php if ($product->isSaleable() || $offers): ?>
    <?php if ($block->isConfigurableProduct()): ?>
        <script>
            require([
                'jquery'
            ], function ($) {
                'use strict';

                $('#tab-label-marketplace_offers').hide();
            });
        </script>

        <div class="block" id="product-offers" style="display: none;">
    <?php else: ?>
        <div class="block" id="product-offers">
    <?php endif; ?>
    <div class="block-content">
        <div class="table-wrapper product-offers">
            <?php if (!count($offers)): ?>
                <p class="review-list-empty"><?= /* @escapeNotVerified */ __('No offers for this selection') ?></p>
            <?php else: ?>
                <table class="data table table-offers" id="product-offers-list">
                    <caption class="table-caption"><?= /* @escapeNotVerified */ __('All Offers') ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="cell label price"><?= /* @escapeNotVerified */ __('Price') ?></th>
                            <th scope="col" class="cell label condition"><?= /* @escapeNotVerified */ __('Condition') ?></th>
                            <?php foreach ($block->getConfigurableAttributes() as $_attribute): ?>
                                <?php /** @var \Magento\Catalog\Model\ResourceModel\Eav\Attribute $_attribute */ ?>
                                <th scope="col" class="cell label <?= /* @escapeNotVerified */ $_attribute->getAttributeCode() ?>">
                                    <?= /* @escapeNotVerified */ $_attribute->getStoreLabel() ?>
                                </th>
                            <?php endforeach ?>
                            <th scope="col" class="cell label seller"><?= /* @escapeNotVerified */ __('Seller') ?></th>
                            <th scope="col" class="cell label shipping" style="display: none;"><?= /* @escapeNotVerified */ __('Shipping Methods') ?></th>
                            <th scope="col" class="cell label qty"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                            <th scope="col" class="cell label actions"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($operatorOffers as $offerResult): ?>
                            <?php /** @var \Magento\Catalog\Model\Product $offer */ ?>
                            <?php $offer = $offerResult['offer']; ?>
                            <tr class="offer offer-1p sku-<?= /* @escapeNotVerified */ $offer->getSku() ?>">
                                <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="cell price" data-price-amount="<?= /* @escapeNotVerified */ $offer->getFinalPrice(1) ?>">
                                   <?= $block->getProductPriceHtml($offer, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Condition')) ?>" class="cell condition">
                                    <div class="offer-state"><?= /* @escapeNotVerified */ __('New') ?></div>
                                    <?php if ($offerResult['stock']): ?>
                                        <div class="offer-stock"><span class="number"><?= /* @escapeNotVerified */ $offerResult['stock']?></span> <?= /* @escapeNotVerified */ __('in stock') ?></div>
                                    <?php endif; ?>
                                </td>
                                <?php foreach ($block->getConfigurableAttributes() as $_attribute): ?>
                                    <?php /** @var \Magento\Catalog\Model\ResourceModel\Eav\Attribute $_attribute */ ?>
                                    <td data-th="<?= $block->escapeHtml($_attribute->getStoreLabel()) ?>" class="cell <?= /* @escapeNotVerified */ $_attribute->getAttributeCode() ?>">
                                        <?= /* @escapeNotVerified */ $block->getProductAttributeValue($offer->getId(), $_attribute) ?>
                                    </td>
                                <?php endforeach ?>
                                <td data-th="<?= $block->escapeHtml(__('Seller')) ?>" class="cell seller">
                                    <?= /* @escapeNotVerified */ $block->getStoreName() ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Shipping Methods')) ?>" class="cell shipping-details" style="display: none;">
                                    <ul class="offer-shipping-details" data-shipping-offer-id="<?= /* @escapeNotVerified */ $offer->getId() ?>"></ul>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="cell qty">
                                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                                    <input class="input-text qty offer-number-qty operator-offer"
                                           type="number"
                                           name="qty"
                                           id="qty-operator-<?= /* @escapeNotVerified */ $offer->getId() ?>"
                                           maxlength="12"
                                           value="<?= $productView ? $productView->getProductDefaultQty($offer) * 1 : 1 ?>"
                                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                           data-validate='<?= /* @escapeNotVerified */ $productView ? json_encode($productView->getQuantityValidators()) : '{"required-number":true,"validate-item-quantity":{"minAllowed":1}}' ?>' />

                                    <?php if ($increment = $block->getProductQtyIncrements($offer)): ?>
                                        <div class="product pricing increment">
                                            <?= /* @escapeNotVerified */ __('Available to buy in increments of %1', $increment) ?>
                                        </div>
                                    <?php endif; ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="cell actions">
                                    <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action primary tocart add-offer-to-cart" data-product="<?= /* @escapeNotVerified */ $offer->getId() ?>">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>

                        <?php foreach ($offers as $offer): ?>
                            <?php /** @var \Mirakl\Connector\Model\Offer $offer */ ?>
                            <tr class="offer offer-3p sku-<?= /* @escapeNotVerified */ $offer->getProductSku() ?>">
                                <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="cell price">
                                    <?= $block->getOfferPriceBlock($offer)
                                              ->setDisplayShippingPrice(false)
                                              ->toHtml() ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Condition')) ?>" class="cell condition">
                                   <div class="offer-state"><?= /* @escapeNotVerified */ __($offer->getConditionName()) ?></div>
                                   <?php if ($offer->getDescription()): ?>
                                       <div class="offer-description"><p><?= $block->escapeHtml($offer->getDescription()) ?></p></div>
                                   <?php endif; ?>
                                   <?php if ($offer->getQuantity()): ?>
                                       <div class="offer-stock"><span class="number"><?= $offer->getQuantity() + 0?></span> <?= /* @escapeNotVerified */ __('in stock') ?></div>
                                   <?php endif; ?>
                                </td>
                                <?php foreach ($block->getConfigurableAttributes() as $_attribute): ?>
                                    <?php /** @var \Magento\Catalog\Model\ResourceModel\Eav\Attribute $_attribute */ ?>
                                    <td data-th="<?= $block->escapeHtml($_attribute->getStoreLabel()) ?>" class="cell <?= /* @escapeNotVerified */ $_attribute->getAttributeCode() ?>">
                                        <?= /* @escapeNotVerified */ $block->getProductAttributeValue($offer->getProductId(), $_attribute) ?>
                                    </td>
                                <?php endforeach ?>
                                <td data-th="<?= $block->escapeHtml(__('Seller')) ?>" class="cell seller">
                                    <?php /** @var \Mirakl\Core\Model\Shop $shop */ ?>
                                    <?php $shop = $block->getOfferHelper()->getOfferShop($offer) ?>
                                    <?php if ($shop): ?>
                                        <?php $evaluation = $shop->getFormattedGrade() ?>
                                        <div class="rating-summary">
                                            <span class="offer-seller-name">
                                                 <a href="<?= $block->escapeUrl($shop->getUrl()) ?>"><?= $this->escapeHtml($shop->getName()) ?></a>
                                            </span>
                                            <?php if ($shop->getEvaluationsCount() > 0): ?>
                                                <div class="rating-result" title="<?= /* @escapeNotVerified */ $evaluation ?>%">
                                                    <span style="width:<?= /* @escapeNotVerified */ $evaluation ?>%"><span><span itemprop="ratingValue"><?= /* @escapeNotVerified */ $evaluation ?></span>% <?= /* @escapeNotVerified */ __('of') ?> <span itemprop="bestRating">100</span></span></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($shop->getEvaluationsCount() > 0): ?>
                                            <div class="offer-seller-rating"><span class="number"><?= /* @escapeNotVerified */ $evaluation ?></span>% <?= /* @escapeNotVerified */ __('positive evaluations') ?></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Shipping Methods')) ?>" class="cell label shipping offer-shipping shipping-options" style="display: none">
                                    <div class="offer-shipping best-offer-shipping" data-shipping-offer-id="<?= /* @escapeNotVerified */ $offer->getId()?>" style="display: none"></div>
                                    <a href="javascript:;"  class="shipping-options-link" data-offer-id="<?= /* @escapeNotVerified */ $offer->getId()?>" style="display: none" >
                                        <?= $block->escapeHtml(__('Shipping Options')) ?>
                                    </a>
                                    <div id="modal-content-<?= /* @escapeNotVerified */ $offer->getId()?>">
                                        <div class="offer-details">
                                            <div class="shop-name">
                                                <?= /* @escapeNotVerified */ __('Sold by:') ?>
                                                <strong><a href="<?= /* @escapeNotVerified */ $offer->getShop()->getUrl()?>"><?= /* @escapeNotVerified */ $offer->getShopName() ?></a></strong>
                                            </div>
                                            <div class="offer-condition">
                                                <?= /* @escapeNotVerified */ __('Condition:') ?>
                                                <strong><?= /* @escapeNotVerified */ $offer->getConditionName() ?></strong>
                                            </div><br>
                                        </div>
                                        <div class="customer-shipping-address" data-offer-id="<?= /* @escapeNotVerified */ $offer->getId()?>"></div>
                                        <div class="offer-shipping-details" data-shipping-offer-id="<?= /* @escapeNotVerified */ $offer->getId()?>"></div>
                                    </div>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="cell qty">
                                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                                    <input class="input-text qty offer-number-qty marketplace-offer"
                                           type="number"
                                           name="qty"
                                           id="qty-<?= /* @escapeNotVerified */ $offer->getId() ?>"
                                           maxlength="12"
                                           value="<?= /* @escapeNotVerified */ $block->getOfferDefaultQty($offer) * 1 ?>"
                                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                           data-validate='<?= $block->escapeHtml(json_encode($block->getOfferQuantityValidators($offer))) ?>' />

                                    <?php if ($offer->getPackageQuantity()): ?>
                                        <div class="product pricing increment">
                                            <?= /* @escapeNotVerified */ __('Available to buy in increments of %1', $offer->getPackageQuantity()) ?>
                                        </div>
                                    <?php endif; ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="cell actions">
                                    <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action primary tocart add-offer-to-cart" data-offer="<?= /* @escapeNotVerified */ $offer->getId() ?>">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
  "*": {
     "Mirakl_FrontendDemo/js/product/view/offer-shipping": {
                "offerShippingUrl" : "<?= /* @escapeNotVerified */ $block->getOfferShippingAjaxUrl(); ?>",
                "addressShippingMethodsUrl" : "<?= /* @escapeNotVerified */ $block->getAddressShippingMethodsAjaxUrl(); ?>"
              },
     "Mirakl_FrontendDemo/js/product/view/mirakl-offers": {}
  }
}
</script>
<script>
    require([
        'jquery'
    ], function ($) {
        'use strict';
        document.product_skus = '<?= /* @escapeNotVerified */ $block->getProductSkusJson(); ?>';
    });
</script>
<?php endif; ?>
