<?php
/**
 * @var \Mirakl\Process\Block\Adminhtml\Process\View\ChildList $block
 */
?>
<section class="admin__page-section process-child-list">
    <div class="admin__page-section-title">
        <span class="title">
            <?= $block->escapeHtml(__('Process Child List')) ?> (<?= /* @escapeNotVerified */ $block->getNbChildren() ?>)
        </span>
    </div>
    <div>
        <?= $block->getChildHtml() ?>
    </div>
</section>
